services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      additional_contexts:
        - project_root=.
    volumes:
      - .:/workspace
    command: sleep infinity
    links:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      additional_contexts:
        - project_root=.
    volumes:
      - .:/workspace
    command: sleep infinity
    extra_hosts:
      - "host.docker.internal:host-gateway"
