FROM python:3.11-slim-bullseye

RUN apt-get update \
        && apt-get -y install ca-certificates \
        && apt-get -y install make \
        && apt-get -y install curl \
        && apt-get -y install git

COPY --from=project_root nscacert.pem /usr/lib/ssl/certs

RUN c_rehash

# so that vscode extensions can install
ENV NODE_EXTRA_CA_CERTS=/usr/lib/ssl/certs/nscacert.pem

RUN curl -sSL https://install.python-poetry.org | python -

RUN echo 'export PATH=$PATH:$HOME/.local/bin' >> ~/.bashrc
